### ISSUE TITLE
Rotation transforms are broken with H/V commands

### ISSUE THREAD

**Issue by nfroidure** [nfroidure/svg-pathdata#27]
## Issue

Rotation transforms are broken
https://github.com/nfroidure/gulp-iconfont/issues/147

### Expected behavior
Rotating the path
### Actual behavior
Error thrown

**Comment by NaridaL** [comment]
Hmm, yeah I changed it so that H and V couldn't be rotated at some point.  The idea was that you need to do a normalizeHVZ pass first before rotating, so they get changed to L instead of H/V. Maybe that's not the best solution. We can either change it so H/V get changed to L when rotating, or you can add a call to normalizeHVZ before transforming in gulp-iconfont.

**Comment by nfroidure** [comment]
@NaridaL sounds good, I'll fix it directly in the `svgicons2svgfont` project then.
